toplevel: "counterConfig_v1_0_S00_AXI_tb"
name: project_config
files: 
  - name: "counterConfig_v1_0_S00_AXI_tb.vhd"
    is_include_file: false
    logical_name: ""
  - name: "counterConfig_v1_0_S00_AXI.vhd"
    is_include_file: false
    logical_name: "mylib"
tool_options: 
  ghdl: 
    installation_path: ""
    waveform: "sim.vcd"
    analyze_options: ""
    run_options: "--stop-time @200ns"