toplevel: "LoopCounter_v1_0_M00_AXIS_tb"
name: project_config
files: 
  - name: "LoopCounter_v1_0_M00_AXIS_tb.vhd"
    is_include_file: false
    logical_name: ""
  - name: "LoopCounter_v1_0_M00_AXIS.vhd"
    is_include_file: false
    logical_name: "mylib"
tool_options: 
  ghdl: 
    installation_path: ""
    waveform: "sim.vcd"
    analyze_options: ""
    run_options: "--stop-time @200ns"